[workspace]
members = [ "crates/bench","crates/light-node", "crates/compile-wasm", "crates/shared"]
resolver = "2"

[workspace.dependencies]
prometheus = "0.13.4"
prometheus_exporter = "0.8.5"
lazy_static = "1"
