data_dir = "/var/lib/vector"

[sources.docker]
type = "docker_logs"
include_containers = ["test-app"]

[sinks.sidecar]
type = "socket"
inputs = ["docker"]
mode = "unix_stream"
path = "/tmp/tangent-sidecar.sock"
encoding.codec = "json"
framing.method = "newline_delimited"
buffer.type = "memory"
buffer.when_full = "block"